apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/RekhuGopal/AWS_EKS_Flux_GitOps
  ref:
    branch: main
  secretRef:
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
